### ISSUE TITLE
Correct ordering of avdl files

### ISSUE THREAD

**Issue by jon-morra-zefr** [julianpeeters/sbt-avrohugger#34] opened 2017-02-06 15:32 UTC
I have a project consisting of a number of avdl files that depend on each other.  On my local Mac I can force everything to work by naming files in alphabetical order.  However, the build fails on an AWS machine.  I'm trying to figure out how files are sorted there, but this seems like something that should be handled by the plugin.  I see [AVSCFileSorter](https://github.com/julianpeeters/sbt-avrohugger/blob/master/src/main/scala/sbtavrohugger/filesorter/AVSCFileSorter.scala) which looks great for avsc files, but, looking at [FileWriter](https://github.com/julianpeeters/sbt-avrohugger/blob/master/src/main/scala/sbtavrohugger/FileWriter.scala) it would appear avdl files are not sorted at all.

I think a sorter for avdl files would be great.

Thanks

**Comment by mariussoutier** [comment] 2017-02-07 09:06
Duplicate of #33.

**Comment by julianpeeters** [comment] 2017-02-13 11:47
fixed in 0.15.0

**Closed by julianpeeters** 2017-02-13 11:47 UTC

**Comment by mariussoutier** [comment] 2017-02-13 13:11
@jon-morra-zefr  Thanks for contributing!
