### ISSUE TITLE
Miss support of logicalType and number of fields

### ISSUE THREAD

**Issue by llyjy21** [julianpeeters/sbt-avrohugger#44] opened 2017-11-24 11:47 UTC
I found two issues:
1. If I wrote fields more than 254, there is a limit of JVM, because the constructor of treehugger.
2. The plugin lacks support of logicalType, which makes the plugin lack of two important types (UUID and BigDecimal)

**Comment by mariussoutier** [comment] 2017-11-24 19:56
1. You should just use sub-records. 254 fields is clearly a code smell.
2. Duplicate of #29 and more of an avrohugger issue, where there's an issue related to this as well: https://github.com/julianpeeters/avrohugger/issues/29

**Comment by llyjy21** [comment] 2017-11-26 16:25
@mariussoutier   hey, marius ? Thank you for your reply. For the issue N.1, actually, I don't agree. Because in some situation (needs of business), there are always possibilities to have more than 254 fields or without sub-records;
On the other side, you know, scala has already omitted limit of parameters for a case class.

Actually, there is already no limit of fields in the java plugin(with Builder in place of constructor).
So I think it will be a bigger problem if the basic principal keeps using constructor.

**Closed** 2018-08-06 06:58 UTC
