### ISSUE TITLE
Regression for `avroScalaGenerateSpecific` since 2.0.0-RC16

### ISSUE THREAD

**Issue by sjbog** [julianpeeters/sbt-avrohugger#76] opened 2019-12-16 13:31 UTC
Using `avroScalaGenerateSpecific` to generate 1 avsc file

- with v2.0.0-RC15 - takes 1-2s
- with v2.0.0-RC16 and later - takes 60s+; latest RC22 is also affected

Setup: Mac 10.14, sbt v1.3.5, openjdk version "1.8.0_232"

Avro
```
{
  "namespace": "ApiService",
  "name": "Event",
  "type": "record",
  "fields": [
    {
      "name": "event_type",
      "doc": "Event type",
      "type": {
        "name": "DPEventType",
        "type": "enum",
        "symbols": [
          "CREATE",
          "UPDATE",
          "DELETE",
          "OTHER"
        ]
      }
    },
    {
      "name": "entity",
      "type": {
        "name": "Entity",
        "type": "record",
        "fields": [
          {
            "name": "auto_id",
            "doc": "unique identifier",
            "type": "long"
          },
          {
            "name": "date_created",
            "doc": "Date of creation",
            "type": "string"
          },
          {
            "name": "date_updated",
            "doc": "Date of update",
            "type": "string"
          },
          {
            "name": "flags",
            "doc": "Bitmask of flag capabilities",
            "type": "long"
          }
        ]
      }
    }
  ]
}
```

**Comment by sjbog** [comment] 2019-12-16 15:25
Tried on another mac, couldn't reproduce.

**Comment by jalaziz** [comment] 2020-05-13 20:43
We've noticed this too. Doesn't always happen, but when it does happen, SBT seemingly is stuck forever on `avroScalaGenerateSpecific`. In our case, it seems to happen specifically to one project in a multi-project build.

**Comment by orElse** [comment] 2020-08-13 06:03
I have a similar issue but for me they start once I introduce enum in the avros - without the enums generation or using string (which is not an option in my production code) instead of JavaEnum, generation time is fine

https://github.com/orElse/sbt_avro_test

also I get this only on macOS and also only on some of my colleagues machines but not on all of them

**Comment by Fattouh92** [comment] 2020-08-13 12:23
we also struggle with the same problem at my workplace. this can be observed on some developers' **Mac** machines and others not. We could not reproduce or find root cause but seems connected to enums. this is really essential to fix as it really affects our productivity greatly

**Comment by orElse** [comment] 2020-08-21 06:53
the main change in the area when this was reported was the the directory for the target of the generated java enum.
It was moved from a fixed one "target/" to System.getProperty("java.io.tmpdir")

if I change the path in my project via .sbtopts & -Djava.io.tmpdir the generation time decreases heavily - I have to check if I ca find out whats wrong with the original tmpdir I get from the system on my mac

**Comment by thomasschoeftner** [comment] 2022-03-01 08:42
Ok now, does anyone know if this is still reproducible with the latest avrohugger release (avrohugger v1.0.0 and sbt-avrohugger v2.0.0)?

**Comment by julianpeeters** [comment] 2022-03-01 16:50
I'm afraid I can't confirm. I'll note that avrohugger's temp dir was changed in `RC26` https://github.com/julianpeeters/avrohugger/pull/148 and I forgot to close this ticket. I expect that the problem was indeed related to using the problematic temp dir, so I'll close this, but please reopen or submit a new issue as needed.

**Closed by julianpeeters** 2022-03-01 16:50 UTC
